import type { OverwatchPublicationInput } from "@/integrations/overwatch/dto";

export const overwatchPublicationFixtures: readonly OverwatchPublicationInput[] = [
  {
    overwatchObjectId: "ow:situation:eastern-corridor:2026-09-25",
    projectId: "monitor:eastern-corridor",
    title: "Eastern Corridor Situation Report: 24-25 September",
    summary: "A time-bounded assessment of transport disruptions across the eastern corridor.",
    body: [
      "Collection between 24 September 18:00 UTC and 25 September 18:00 UTC identified delays at three eastern corridor crossings.",
      "Independent public reporting corroborates queue growth, but the duration of the disruption remains uncertain.",
    ],
    publicationType: "situation-report",
    slug: "eastern-corridor-situation-report-2026-09-25",
    tags: ["situation-report", "eastern-corridor", "transport"],
    visibility: "public",
    readingTimeMinutes: 6,
    citations: [
      {
        id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
        title: "Eastern Corridor Border Notice",
        authors: ["Eastern Corridor Authority"],
        publisher: "Eastern Corridor Authority",
        publishedAt: "2026-09-25",
        url: "https://example.org/eastern-corridor-border-notice",
      },
      {
        id: "a1a1a1a1-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
        title: "Freight Queue Monitoring Update",
        authors: ["Regional Transport Observatory"],
        publisher: "Regional Transport Observatory",
        publishedAt: "2026-09-25",
        url: "https://example.org/freight-queue-update",
      },
    ],
    evidenceIds: [
      "11111111-1111-4111-8111-111111111111",
      "12121212-1212-4121-8121-121212121212",
    ],
    assessment: {
      confidenceLevel: "moderate",
      assessmentDate: "2026-09-25",
      sourceCount: 4,
      corroborationStatus: "corroborated by independent public reporting",
      collectionWindow: "2026-09-24T18:00:00Z to 2026-09-25T18:00:00Z",
      geographicScope: "Eastern Corridor crossings and adjacent freight routes",
      temporalScope: "Reporting period ending 2026-09-25",
      analyticCaveats: [
        "Commercial imagery coverage was incomplete during the final six hours of the collection window.",
        "Observed queues do not establish the cause or expected duration of the disruption.",
      ],
    },
    seriesId: "eastern-corridor-daily-situation-report",
    reportingPeriod: "2026-09-24/2026-09-25",
  },
  {
    overwatchObjectId: "ow:brief:strategic-logistics:2026-q3",
    projectId: "workspace:strategic-analysis",
    title: "Strategic Intelligence Brief: Corridor Resilience",
    summary: "A synthesized assessment of the eastern corridor's resilience to continued disruption.",
    body: [
      "The available reporting indicates that alternate routes can absorb short disruptions but not sustained restrictions at multiple crossings.",
      "The assessment combines official notices, freight monitoring, and historical routing patterns.",
      "Further collection is needed to distinguish temporary congestion from a deliberate restriction.",
    ],
    publicationType: "intelligence-brief",
    slug: "strategic-intelligence-brief-corridor-resilience",
    tags: ["intelligence", "strategic-analysis", "logistics"],
    visibility: "public",
    readingTimeMinutes: 9,
    citations: [
      {
        id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
        title: "Regional Freight Capacity Review",
        authors: ["Regional Transport Observatory"],
        publisher: "Regional Transport Observatory",
        publishedAt: "2026-09-18",
        url: "https://example.org/freight-capacity-review",
      },
      {
        id: "b1b1b1b1-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
        title: "Crossing Throughput Statistics",
        authors: ["Eastern Corridor Authority"],
        publisher: "Eastern Corridor Authority",
        publishedAt: "2026-09-24",
        url: "https://example.org/crossing-throughput",
      },
      {
        id: "b2b2b2b2-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
        title: "Open Freight Routing Data",
        authors: ["Open Logistics Exchange"],
        url: "https://example.org/open-routing-data",
      },
    ],
    evidenceIds: ["13131313-1313-4131-8131-131313131313"],
    assessment: {
      confidenceLevel: "moderate",
      assessmentDate: "2026-09-25",
      sourceCount: 7,
      corroborationStatus: "partially corroborated",
      geographicScope: "Eastern Corridor and alternate regional freight routes",
      temporalScope: "July to September 2026",
      analyticCaveats: [
        "Capacity estimates assume normal fuel availability and border processing conditions.",
        "The available reporting cannot attribute observed disruption to a specific actor.",
      ],
      methodologyNote: "Structured comparison of official throughput data, open freight-routing data, and historical disruption patterns.",
      confidenceRationale: "Independent official and commercial sources agree on limited spare capacity; route-level observations remain incomplete.",
    },
  },
  {
    overwatchObjectId: "ow:monitoring:port-activity:2026-09-25",
    projectId: "monitor:port-activity",
    title: "Port Activity Monitoring Dispatch: 25 September AM",
    summary: "No material change was observed during the morning monitoring window.",
    body: ["No material change was observed between 06:00 UTC and 12:00 UTC."],
    publicationType: "short-dispatch",
    slug: "port-activity-monitoring-dispatch-2026-09-25-am",
    tags: ["monitoring"],
    visibility: "public",
    readingTimeMinutes: 1,
    citations: [{
      id: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
      title: "Port Operations Notice",
      authors: ["Port Authority"],
      url: "https://example.org/port-operations-notice",
    }],
    evidenceIds: ["14141414-1414-4141-8141-141414141414"],
    assessment: {
      confidenceLevel: "low",
      temporalScope: "2026-09-25 06:00-12:00 UTC",
    },
    seriesId: "port-activity",
    reportingPeriod: "2026-09-25T06:00:00Z/2026-09-25T12:00:00Z",
  },
];
